apiVersion: v1
kind: Service
metadata:
  name: {{ include "gate.fullname" . }}-http
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gate.labels" . | nindent 4 }}
  {{- with .Values.http.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.http.service.type }}
  ports:
    - name: http
      port: {{ .Values.http.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "gate.selectorLabels" . | nindent 4 }}
