apiVersion: v1
kind: Service
metadata:
  name: {{ include "gate.fullname" . }}-ssh
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gate.labels" . | nindent 4 }}
  {{- with .Values.ssh.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ssh.service.type }}
  ports:
    - name: ssh
      port: {{ .Values.ssh.service.port }}
      targetPort: ssh
      protocol: TCP
  selector:
    {{- include "gate.selectorLabels" . | nindent 4 }}
  {{- if and (eq .Values.ssh.service.type "LoadBalancer") .Values.ssh.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.ssh.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
